services:
  # 1. Tu Aplicación Web
  mi-web-python:
    build: .
    container_name: mi_web_python
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - db  # Esperar a que la base de datos arranque
    environment:
      # OJO ACÁ: Cambiamos 'localhost' por 'db' (el nombre del servicio de abajo)
      - DATABASE_URL=postgresql://drPiscinas:administrador@db:5432/drPiscinas_db
      - SECRET_KEY=${SECRET_KEY}

  # 2. La Base de Datos (PostgreSQL)
  db:
    image: postgres:15
    container_name: mi_base_datos
    restart: always
    environment:
      POSTGRES_USER: drPiscinas
      POSTGRES_PASSWORD: administrador
      POSTGRES_DB: drPiscinas_db
    volumes:
      - db_data:/var/lib/postgresql/data

# 3. Volumen para que no se borren los datos si reiniciás
volumes:
  db_data: